bolsistas_praec/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views  

app_name = 'bolsistas_praec'
urlpatterns = [
	url(r'^index/$', views.index, name='index'),
    url(r'^registro/$', views.registrar_usuario, name='registrar_usuario'),  
    url(r'^addAluno/$', views.alunoCreateView.as_view(), name='add_aluno'),    
    url(r'^alunos/(?P<pk>\d+)$', views.aluno_detail.as_view(), name='aluno_detail'),
]

praec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('bolsistas_praec.urls', namespace='bolsistas_praec'))
]

bolsistas_praec/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Aluno (models.Model):
    matricula = models.CharField(max_length=15,primary_key=True)
    nome = models.CharField(max_length=80)
    cpf = models.CharField(max_length=15)
    curso = models.CharField(max_length=80)
    periodo = models.CharField(max_length=15, null=True)
    renda_familiar = models.CharField(max_length=15)
    data_preenchimento = models.DateField()
    data_preenchimento_termino = models.DateField()
    #nome_Inst = models.CharField(max_length=80)
    #prazo de 23 meses -> 

    def get_absolute_url(self):
        return reverse('bolsistas_praec:aluno_detail', args=[str(self.matricula)]) 

    def __str__(self):
        return self.nome

class Siape(models.Model):
    siape = models.CharField(max_length=9)

    def __str_(self):
        return self.siape

class Usuario (models.Model):
#siape é a matrícula dos servidores
    siape = models.CharField(max_length=20, primary_key=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    def publish(self):
        self.save()

    def __str__(self):
        return self.siape

        #renda máxima 1405,50 reais
class Bolsa_Auxilio (models.Model):
    aluno = models.OneToOneField(Aluno,on_delete=models.CASCADE)    #chave estrangeira
    tipo_bolsa_auxilio = (
        ('REU','REU'),
        ('ITA','ITA'),
        ('KIT ODONTOLOGICO','KIT ODONTOLOGICO'),
        ('KIT LUPAS MANUAIS','KIT LUPAS MANUAIS')
        )
    tipo = models.CharField(max_length=17,choices=tipo_bolsa_auxilio)

#auxílio creche -> 3 anos e 10 meses - aviso prazo máximo de 3 anos e 11 meses
class Bolsa_Remunerada_400(models.Model):
    aluno = models.OneToOneField(Aluno,on_delete=models.CASCADE)
    tipo_bolsa_remunerada = (
        ('BAE','BAE'),
        ('BIAMA','BIAMA'),
        ('BINCS','BINCS'),
        ('APEC','APEC'),
        ('BIAE','BIAE'),
        ('BIAF','BIAF')
        )
    tipo = models.CharField(max_length=5,choices=tipo_bolsa_remunerada)
    
#emergencial de 3 meses quando o aluno precisa fora do prazo do edital (pode edital de Bae)
#- dependendo da data do edital o aluno reccebe a diferença dos 24 meses da BAE

bolsistas_praec/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.conf import settings

class UserForm(forms.ModelForm):
    password = forms.CharField(
        required = True,
        label = 'Senha',
        max_length = 32,
        min_length = 8,
        widget = forms.PasswordInput()
    )
    username = forms.CharField(
        required = True,
        label = 'Nome do usuário',
        max_length = 150,
        help_text = ""
    )
    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')
        labels = {
            'username': 'Nome de usuário',
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'password': 'Senha',
        }

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('siape',)
        labels = {
            'siape': 'Código SIAPE',
        }


#username = forms.CharField(label=u'Username', max_length=30)
#    first_name = forms.CharField(label=u'First Name', max_length=30)
#    last_name = forms.CharField(label=u'Last Name', max_length=30)
#    email = forms.EmailField(label=u'Email')
#    password1 = forms.CharField(
#                               label=u'Password',
#                               widget=forms.PasswordInput()
#                               )
#   password2 = forms.CharField(
#                               label=u'Password (Again)',
#                               widget=forms.PasswordInput()
#                              )  

class AlunoForm(forms.ModelForm):

    data_preenchimento = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    data_preenchimento_termino = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
     
    class Meta:
        model = Aluno
        fields = '__all__'
        labels = {
	    'nome': 'Nome do aluno',
	    'matricula': 'Matricula do aluno',
	    'curso': 'Curso do aluno',
	    'periodo': 'Periodo do aluno no curso',
	    'renda_familiar': 'Renda familiar do aluno',
	    'cpf': 'CPF do aluno',
	    'data_preenchimento': 'Data de Preenchimento do cadastro',
        'data_preenchimento_termino': 'Data de Término do cadastro',
	};

class Bolsa_AuxilioForm(forms.ModelForm):
    #pesquisa o aluno e vincula a bolsa
    class Meta:
        model = Bolsa_Auxilio
        fields = ('tipo',)
        labels = {
            'tipo': 'Tipo de Bolsa Auxílio',
        }

class Bolsa_Remunerada_400Form(forms.ModelForm):
    class Meta:
        model = Bolsa_Remunerada_400
        fields = ('tipo',)
        labels = {
             'tipo': 'Tipo de Bolsa Remunerada',
        }

bolsistas_praec/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Siape,Usuario,Aluno
# Create your views here.
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from .forms import *
from django.views import generic

@login_required
def index(request):
    
    my_object = Siape.objects.filter(siape = request.user.usuario.siape)
    if my_object.count() == 0:
        return HttpResponse ("O SIAPE não é válido!")
    return render(request, 'bolsistas_praec/praec.html', {})


class alunoCreateView(CreateView):
    model = Aluno
    form_class = AlunoForm

class aluno_detail(generic.DetailView):
    model = Aluno
    
def registrar_usuario(request):
#    if request.user.is.authenticated:
#       return redirect('bolsistas_praec: ')
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        usuario_form = UsuarioForm(data=request.POST)
        if user_form.is_valid() and usuario_form.is_valid():
            user = user_form.save(commit=False)
            usuario = usuario_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            usuario.usuario = user
            usuario.save()
            return redirect('/accounts/login')
        else:
            user_form = UserForm()
            usuario_form = UsuarioForm()
        return render(request, 'bolsistas_praec/templates/registration/login.html',
                      {'user_form': user_form,
                       'usuario_form': usuario_form})
    

bolsistas_praec/templates/base.html
{% load staticfiles %}
<html >
    <head>
        <meta charset="UTF-8">
  		<title>Sign-Up/Login Form</title>
  		<link href='https://fonts.googleapis.com/css?family=Titillium+Web:300,500,700' rel='stylesheet' type='text/css'>
  		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  		<link rel="stylesheet" href="/static/css/style.css">




  		<title>Cadastro/Cadastro Form</title>
  		<link href='https://fonts.googleapis.com/css?family=Titillium+Web:300,500,700' rel='stylesheet' type='text/css'>
  		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  		<link rel="stylesheet" href="/static/css/style.css">


	</head>
	<body>
	    <div class="teste">
	        {% block content %}
	        {% endblock %}
	    </div>
	</body>
</html>>

bolsistas_praec/templates/bolsistas_praec/aluno_form.html
{% extends 'base.html' %}
{% block content %}



<head>
  <meta charset="UTF-8">
  <title>Cadastrar/Cadastro Form</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
</head>


<!--<div class="form" align="center">-->
<form action="" enctype="" method="post"  align = "center"  novalidate=""> 
<div class="form" align="center">
	{% csrf_token %}

	<table>
		<h2>
  		 <table><h2>Cadastro do aluno</h2></table>
			{{form.as_ul}}<br>
		</h2>>
	</table>
	<br><br>
	<button type="submit" style="">Criar</button>
	<!--<input type="submit" value="Cadastrar">  -->

        <br><br><br>
        <input type="hidden" name="next" value="{% url 'bolsistas_praec:index' %}"/>         

    <h1><a href="{% url 'bolsistas_praec:index' %}"></a></h1> 
</div>
</form>

<!--</div>-->
{% endblock %} 

bolsistas_praec/templates/bolsistas_praec/praec.html
{% extends 'base.html' %}
{% block content %}
	<div class="form" align="center">
		<head>
			<title>PRAEC</title>
		</head>
	    <h2>FUNCIONALIDADES</h2>
		<h2><a href= "{% url 'bolsistas_praec:add_aluno' %}" >Cadastrar Aluno</a></h2>
		<h2><a href= "{% url 'bolsistas_praec:add_aluno' %}" >Modificar Aluno</a></h2>    <!--  deve ser no listar alunos. Em 																					  seguida modifica_cadastro.  																					      	   -->
</div>  


{% endblock %}

bolsistas_praec/templates/bolsistas_praec/registrar_usuario.html
<!--    {% extends 'bolsistas_praec/base.html' %}
{% block content %}
<head>
{% endblock %}   -->